import io
import pandas as pd

new_csv_content = """text,intent
"Can you help me with Python?","python"
"I need help debugging Python.","python"
"I'm stuck with a Python function.","python"
"Can you explain this Python error?","python"
"I need assistance with a Python script.","python"
"Help me understand Python dictionaries.","python"
"Can you teach me Python?","python"
"I'm confused about Python decorators.","python"
"I have a problem with my Python code.","python"
"Can you guide me through Python loops?","python"
"Can you help me understand Python?","python"
"I am having an issue with python lists.","python"
"Please assist me with this python bug.","python"
"I have a question regarding python syntax.","python"
"Could you help me fix my python code?","python"
"I am stuck on a python assignment.","python"
"Explain how python list comprehensions work, please.","python"
"I need some guidance on python classes.","python"
"Can someone help me troubleshoot this python script?","python"
"I am confused by python's kwargs.","python"
"Having a problem getting my python program to run.","python"
"Teach me how to use python virtual environments.","python"
"I need help understanding python generators.","python"
"Guide me through setting up python on my machine.","python"
"I'm stuck trying to import a python module.","python"
"Can you explain why my python loop is infinite?","python"
"I need assistance reading a file in python.","python"
"Help me resolve this python indentation error.","python"
"I have an issue with python string formatting.","python"
"Can you help me write a python function?","python"
"I'm completely stuck on this python logic.","python"
"Need help with a python problem right now.","python"
"Explain python inheritance to me, I'm confused.","python"
"Can you teach me python web scraping?","python"
"I require assistance with python pandas.","python"
"Having trouble with a python tuple.","python"
"Help me figure out this python traceback.","python"
"I'm confused about python global variables.","python"
"Can you guide me through python regex?","python"
"I need help with python type hinting.","python"
"Problem with my python installation, can you assist?","python"
"Explain python lambda functions, I need help.","python"
"Stuck on a python data structure issue.","python"
"Can you help me learn python from scratch?","python"
"I have a question about python exception handling.","python"
"Please help me understand python dunder methods.","python"
"I need help optimizing my python code.","python"
"Can you assist me in writing a python class?","python"
"I'm facing a problem with python multithreading.","python"
"Explain python async await, I am stuck.","python"
"Need a guide for python file operations.","python"
"Help me fix this python syntax error.","python"
"I'm confused about how python handles memory.","python"
"Can you help me with python API requests?","python"
"I need assistance deploying a python app.","python"
"Having an issue with python pip install.","python"
"Teach me python object oriented programming.","python"
"Can you guide me on python best practices?","python"
"I have a python question I need help with.","python"
"Help me understand the python self keyword.","python"
"I'm stuck on a python coding challenge.","python"
"Can you explain python context managers?","python"
"I need help creating a python GUI.","python"
"Problem with python recursion, please help.","python"
"Assist me with my python homework.","python"
"I am confused by python decorators and need an explanation.","python"
"Can you help me debug a python dictionary error?","python"
"I need help understanding python sets.","python"
"Guide me through writing a python script.","python"
"I have an issue with my python environment.","python"
"Can you teach me python data analysis?","python"
"Help me with this python math problem.","python"
"I'm stuck on python string manipulation.","python"
"Explain how python modules work, I need help.","python"
"Can you assist me with a python array?","python"
"I have a problem understanding python scoping.","python"
"Need help figuring out a python bug.","python"
"Can you guide me through python unit testing?","python"
"I'm confused about python iterators.","python"
"Help me solve this python logic error.","python"
"I need assistance parsing JSON in python.","python"
"Can you explain python error handling?","python"
"Stuck with a python package issue.","python"
"I have a question about python variables.","python"
"Please help me with python date and time.","python"
"Can you teach me python multiprocessing?","python"
"I need help writing a python while loop.","python"
"Guide me through python list methods.","python"
"I am facing an issue with python plotting.","python"
"Help me understand python boolean logic.","python"
"Can you assist me with python requests library?","python"
"I'm confused by python imports.","python"
"Problem with python indexing, need help.","python"
"Can you explain python slicing to me?","python"
"I need help building a python project.","python"
"Stuck on python object attributes.","python"
"Help me with my python syntax problem.","python"
"Can you guide me on python frameworks?","python"
"I have an issue running my python code.","python"
"Need assistance with python input and output.","python"
"Can you help me with JavaScript?","javascript"
"I need help debugging my JavaScript.","javascript"
"I'm stuck with a JavaScript promise.","javascript"
"Can you explain this JS error?","javascript"
"Help me understand closures in JavaScript.","javascript"
"I need assistance with an async JavaScript function.","javascript"
"Can you guide me through JavaScript arrays?","javascript"
"Can you help me understand JavaScript?","javascript"
"I have a problem with my JavaScript code.","javascript"
"Please assist me with this JS bug.","javascript"
"I have a question regarding JavaScript syntax.","javascript"
"Could you help me fix my JS script?","javascript"
"I am stuck on a JavaScript assignment.","javascript"
"Explain how JavaScript arrow functions work, please.","javascript"
"I need some guidance on JavaScript objects.","javascript"
"Can someone help me troubleshoot this JS event listener?","javascript"
"I am confused by JavaScript hoisting.","javascript"
"Having a problem getting my JavaScript to run.","javascript"
"Teach me how to use JavaScript fetch API.","javascript"
"I need help understanding JavaScript callbacks.","javascript"
"Guide me through setting up Node.js.","javascript"
"I'm stuck trying to manipulate the DOM with JS.","javascript"
"Can you explain why my JavaScript loop is broken?","javascript"
"I need assistance reading JSON in JavaScript.","javascript"
"Help me resolve this JS type error.","javascript"
"I have an issue with JavaScript string methods.","javascript"
"Can you help me write a JavaScript function?","javascript"
"I'm completely stuck on this JS logic.","javascript"
"Need help with a JavaScript problem right now.","javascript"
"Explain JavaScript prototypal inheritance to me, I'm confused.","javascript"
"Can you teach me JavaScript async await?","javascript"
"I require assistance with JavaScript map and filter.","javascript"
"Having trouble with a JS array reduce.","javascript"
"Help me figure out this JavaScript console error.","javascript"
"I'm confused about JavaScript scope.","javascript"
"Can you guide me through JavaScript regex?","javascript"
"I need help with JavaScript variable declarations.","javascript"
"Problem with my JS installation, can you assist?","javascript"
"Explain JavaScript event bubbling, I need help.","javascript"
"Stuck on a JavaScript data structure issue.","javascript"
"Can you help me learn JavaScript from scratch?","javascript"
"I have a question about JS exception handling.","javascript"
"Please help me understand the JavaScript this keyword.","javascript"
"I need help optimizing my JS code.","javascript"
"Can you assist me in writing a JavaScript class?","javascript"
"I'm facing a problem with JavaScript timing events.","javascript"
"Explain JS promises to me, I am stuck.","javascript"
"Need a guide for JavaScript local storage.","javascript"
"Help me fix this JavaScript syntax error.","javascript"
"I'm confused about how JavaScript handles memory.","javascript"
"Can you help me with JS API requests?","javascript"
"I need assistance deploying a Node app.","javascript"
"Having an issue with npm install in JS.","javascript"
"Teach me JavaScript object oriented programming.","javascript"
"Can you guide me on JS best practices?","javascript"
"I have a JS question I need help with.","javascript"
"Help me understand JavaScript strict mode.","javascript"
"I'm stuck on a JavaScript coding challenge.","javascript"
"Can you explain JavaScript modules?","javascript"
"I need help creating a JavaScript UI.","javascript"
"Problem with JS recursion, please help.","javascript"
"Assist me with my JavaScript homework.","javascript"
"I am confused by JavaScript destructuring and need an explanation.","javascript"
"Can you help me debug a JS object error?","javascript"
"I need help understanding JavaScript sets.","javascript"
"Guide me through writing a Node script.","javascript"
"I have an issue with my JavaScript environment.","javascript"
"Can you teach me JavaScript DOM manipulation?","javascript"
"Help me with this JS math problem.","javascript"
"I'm stuck on JavaScript string interpolation.","javascript"
"Explain how JS imports work, I need help.","javascript"
"Can you assist me with a JS array sort?","javascript"
"I have a problem understanding JS lexical scoping.","javascript"
"Need help figuring out a JavaScript bug.","javascript"
"Can you guide me through JS unit testing?","javascript"
"I'm confused about JavaScript iterators.","javascript"
"Help me solve this JS logic error.","javascript"
"I need assistance parsing JSON in JS.","javascript"
"Can you explain JavaScript error handling?","javascript"
"Stuck with a JS package issue.","javascript"
"I have a question about JS let and const.","javascript"
"Please help me with JavaScript date and time.","javascript"
"Can you teach me JS concurrency?","javascript"
"I need help writing a JS while loop.","javascript"
"Guide me through JS array methods.","javascript"
"I am facing an issue with JS canvas plotting.","javascript"
"Help me understand JS boolean logic.","javascript"
"Can you assist me with JS fetch library?","javascript"
"I'm confused by JavaScript exports.","javascript"
"Problem with JS indexing, need help.","javascript"
"Can you explain JS slicing to me?","javascript"
"I need help building a JavaScript project.","javascript"
"Stuck on JS object attributes.","javascript"
"Help me with my JavaScript syntax problem.","javascript"
"Can you guide me on JS frameworks?","javascript"
"I have an issue running my JS code.","javascript"
"Need assistance with JavaScript input and output.","javascript"
"Can you help me understand machine learning?","machine_learning"
"I'm stuck understanding overfitting.","machine_learning"
"Can you explain gradient descent?","machine_learning"
"I need help training an ML model.","machine_learning"
"Help me understand classification.","machine_learning"
"Can you guide me through confusion matrices?","machine_learning"
"I'm confused about supervised learning.","machine_learning"
"I need assistance with my machine learning homework.","machine_learning"
"Can you help me with deep learning concepts?","machine_learning"
"I have a problem with my neural network.","machine_learning"
"Please assist me with this ML algorithm.","machine_learning"
"I have a question regarding machine learning models.","machine_learning"
"Could you help me fix my ML training script?","machine_learning"
"I am stuck on an AI assignment.","machine_learning"
"Explain how support vector machines work, please.","machine_learning"
"I need some guidance on unsupervised learning.","machine_learning"
"Can someone help me troubleshoot this ML pipeline?","machine_learning"
"I am confused by machine learning epochs.","machine_learning"
"Having a problem getting my ML model to converge.","machine_learning"
"Teach me how to use machine learning libraries.","machine_learning"
"I need help understanding deep learning layers.","machine_learning"
"Guide me through setting up a machine learning environment.","machine_learning"
"I'm stuck trying to tune ML hyperparameters.","machine_learning"
"Can you explain why my machine learning model is underfitting?","machine_learning"
"I need assistance building a machine learning classifier.","machine_learning"
"Help me resolve this ML dimension error.","machine_learning"
"I have an issue with machine learning feature selection.","machine_learning"
"Can you help me write an ML training loop?","machine_learning"
"I'm completely stuck on this ML logic.","machine_learning"
"Need help with a machine learning problem right now.","machine_learning"
"Explain backpropagation to me, I'm confused.","machine_learning"
"Can you teach me reinforcement learning?","machine_learning"
"I require assistance with ML cross-validation.","machine_learning"
"Having trouble with an ML loss function.","machine_learning"
"Help me figure out this machine learning metric.","machine_learning"
"I'm confused about ML batch sizes.","machine_learning"
"Can you guide me through natural language processing?","machine_learning"
"I need help with machine learning regression.","machine_learning"
"Problem with my ML dataset split, can you assist?","machine_learning"
"Explain K-means clustering, I need help.","machine_learning"
"Stuck on a machine learning optimization issue.","machine_learning"
"Can you help me learn machine learning from scratch?","machine_learning"
"I have a question about ML activation functions.","machine_learning"
"Please help me understand the ML bias-variance tradeoff.","machine_learning"
"I need help optimizing my machine learning model.","machine_learning"
"Can you assist me in writing an ML algorithm?","machine_learning"
"I'm facing a problem with machine learning evaluation.","machine_learning"
"Explain ML decision trees to me, I am stuck.","machine_learning"
"Need a guide for machine learning deployment.","machine_learning"
"Help me fix this ML syntax error.","machine_learning"
"I'm confused about how ML models generalize.","machine_learning"
"Can you help me with ML predictions?","machine_learning"
"I need assistance deploying an ML API.","machine_learning"
"Having an issue with ML library installation.","machine_learning"
"Teach me machine learning fundamentals.","machine_learning"
"Can you guide me on ML best practices?","machine_learning"
"I have an ML question I need help with.","machine_learning"
"Help me understand machine learning weights.","machine_learning"
"I'm stuck on a machine learning coding challenge.","machine_learning"
"Can you explain machine learning regularization?","machine_learning"
"I need help creating a machine learning pipeline.","machine_learning"
"Problem with ML feature extraction, please help.","machine_learning"
"Assist me with my machine learning project.","machine_learning"
"I am confused by ML embeddings and need an explanation.","machine_learning"
"Can you help me debug an ML dimension mismatch?","machine_learning"
"I need help understanding machine learning tensors.","machine_learning"
"Guide me through writing a deep learning script.","machine_learning"
"I have an issue with my ML environment.","machine_learning"
"Can you teach me machine learning data prep?","machine_learning"
"Help me with this ML math problem.","machine_learning"
"I'm stuck on machine learning data augmentation.","machine_learning"
"Explain how ML optimizers work, I need help.","machine_learning"
"Can you assist me with an ML matrix operation?","machine_learning"
"I have a problem understanding ML learning rates.","machine_learning"
"Need help figuring out a machine learning bug.","machine_learning"
"Can you guide me through ML model testing?","machine_learning"
"I'm confused about machine learning early stopping.","machine_learning"
"Help me solve this ML logic error.","machine_learning"
"I need assistance parsing data for ML.","machine_learning"
"Can you explain machine learning evaluation metrics?","machine_learning"
"Stuck with an ML package issue.","machine_learning"
"I have a question about ML variables.","machine_learning"
"Please help me with machine learning time series.","machine_learning"
"Can you teach me ML random forests?","machine_learning"
"I need help writing an ML training loop.","machine_learning"
"Guide me through ML clustering methods.","machine_learning"
"I am facing an issue with ML graph plotting.","machine_learning"
"Help me understand ML probabilistic logic.","machine_learning"
"Can you assist me with ML deep networks?","machine_learning"
"I'm confused by machine learning imports.","machine_learning"
"Problem with ML tensor indexing, need help.","machine_learning"
"Can you explain ML reshaping to me?","machine_learning"
"I need help building a machine learning project.","machine_learning"
"Stuck on ML model attributes.","machine_learning"
"Help me with my machine learning syntax problem.","machine_learning"
"Can you guide me on ML frameworks?","machine_learning"
"I have an issue running my ML code.","machine_learning"
"Need assistance with machine learning input and output.","machine_learning"
"Can you help me with data science?","data_science"
"I need help cleaning my dataset.","data_science"
"I'm stuck handling missing values.","data_science"
"Can you explain exploratory data analysis?","data_science"
"Help me understand standard deviation.","data_science"
"I need assistance with data visualization.","data_science"
"Can you guide me through feature scaling?","data_science"
"Can you help me understand data science?","data_science"
"I have a problem with my data analysis.","data_science"
"Please assist me with this dataset bug.","data_science"
"I have a question regarding data science statistics.","data_science"
"Could you help me fix my data cleaning script?","data_science"
"I am stuck on a data science assignment.","data_science"
"Explain how PCA works in data science, please.","data_science"
"I need some guidance on data wrangling.","data_science"
"Can someone help me troubleshoot this data visualization?","data_science"
"I am confused by data science p-values.","data_science"
"Having a problem getting my data science notebook to run.","data_science"
"Teach me how to use data science libraries.","data_science"
"I need help understanding data science correlation.","data_science"
"Guide me through setting up a data science environment.","data_science"
"I'm stuck trying to merge datasets in data science.","data_science"
"Can you explain why my data science plot is broken?","data_science"
"I need assistance reading CSVs in data science.","data_science"
"Help me resolve this data type error.","data_science"
"I have an issue with data science string methods.","data_science"
"Can you help me write a data science function?","data_science"
"I'm completely stuck on this data logic.","data_science"
"Need help with a data science problem right now.","data_science"
"Explain data distributions to me, I'm confused.","data_science"
"Can you teach me data science forecasting?","data_science"
"I require assistance with data aggregation.","data_science"
"Having trouble with a data science groupby.","data_science"
"Help me figure out this data science outlier.","data_science"
"I'm confused about data science normalization.","data_science"
"Can you guide me through data science dashboards?","data_science"
"I need help with data science variable encoding.","data_science"
"Problem with my data science installation, can you assist?","data_science"
"Explain data imputation, I need help.","data_science"
"Stuck on a data science structure issue.","data_science"
"Can you help me learn data science from scratch?","data_science"
"I have a question about data science exception handling.","data_science"
"Please help me understand the data science workflow.","data_science"
"I need help optimizing my data science code.","data_science"
"Can you assist me in writing a data science class?","data_science"
"I'm facing a problem with data science time series.","data_science"
"Explain data science hypothesis testing to me, I am stuck.","data_science"
"Need a guide for data science SQL queries.","data_science"
"Help me fix this data science syntax error.","data_science"
"I'm confused about how data science handles memory.","data_science"
"Can you help me with data science API requests?","data_science"
"I need assistance deploying a data app.","data_science"
"Having an issue with data science package install.","data_science"
"Teach me data science analytics programming.","data_science"
"Can you guide me on data science best practices?","data_science"
"I have a data science question I need help with.","data_science"
"Help me understand data science A/B testing.","data_science"
"I'm stuck on a data science coding challenge.","data_science"
"Can you explain data science metrics?","data_science"
"I need help creating a data science report.","data_science"
"Problem with data science recursion, please help.","data_science"
"Assist me with my data science homework.","data_science"
"I am confused by data science destructuring and need an explanation.","data_science"
"Can you help me debug a data object error?","data_science"
"I need help understanding data science sets.","data_science"
"Guide me through writing a data script.","data_science"
"I have an issue with my data science environment.","data_science"
"Can you teach me data science manipulation?","data_science"
"Help me with this data science math problem.","data_science"
"I'm stuck on data science interpolation.","data_science"
"Explain how data imports work, I need help.","data_science"
"Can you assist me with a data array sort?","data_science"
"I have a problem understanding data science scoping.","data_science"
"Need help figuring out a data science bug.","data_science"
"Can you guide me through data science unit testing?","data_science"
"I'm confused about data science iterators.","data_science"
"Help me solve this data logic error.","data_science"
"I need assistance parsing JSON in data science.","data_science"
"Can you explain data science error handling?","data_science"
"Stuck with a data package issue.","data_science"
"I have a question about data science let and const.","data_science"
"Please help me with data science date and time.","data_science"
"Can you teach me data science concurrency?","data_science"
"I need help writing a data science while loop.","data_science"
"Guide me through data science array methods.","data_science"
"I am facing an issue with data science plotting.","data_science"
"Help me understand data science boolean logic.","data_science"
"Can you assist me with data science libraries?","data_science"
"I'm confused by data science exports.","data_science"
"Problem with data indexing, need help.","data_science"
"Can you explain data slicing to me?","data_science"
"I need help building a data science project.","data_science"
"Stuck on data object attributes.","data_science"
"Help me with my data science syntax problem.","data_science"
"Can you guide me on data science frameworks?","data_science"
"I have an issue running my data code.","data_science"
"Need assistance with data science input and output.","data_science"
"Can you help me build a website?","web_development"
"I'm stuck with my React website.","web_development"
"Can you explain REST APIs?","web_development"
"I need help with responsive web design.","web_development"
"Help me understand CORS.","web_development"
"I'm having trouble with HTML and CSS.","web_development"
"Can you guide me through deploying a web application?","web_development"
"Can you help me understand web development?","web_development"
"I have a problem with my frontend code.","web_development"
"Please assist me with this CSS bug.","web_development"
"I have a question regarding HTML syntax.","web_development"
"Could you help me fix my web backend script?","web_development"
"I am stuck on a web development assignment.","web_development"
"Explain how flexbox works, please.","web_development"
"I need some guidance on web hosting.","web_development"
"Can someone help me troubleshoot this website error?","web_development"
"I am confused by web development routing.","web_development"
"Having a problem getting my website to run.","web_development"
"Teach me how to use web development frameworks.","web_development"
"I need help understanding web sessions.","web_development"
"Guide me through setting up a local web server.","web_development"
"I'm stuck trying to center a div in web development.","web_development"
"Can you explain why my web layout is broken?","web_development"
"I need assistance reading API responses in web development.","web_development"
"Help me resolve this HTTP error.","web_development"
"I have an issue with web accessibility standards.","web_development"
"Can you help me write a web development function?","web_development"
"I'm completely stuck on this UI logic.","web_development"
"Need help with a web development problem right now.","web_development"
"Explain web authentication to me, I'm confused.","web_development"
"Can you teach me web development SEO?","web_development"
"I require assistance with web forms.","web_development"
"Having trouble with a web development database connection.","web_development"
"Help me figure out this web console error.","web_development"
"I'm confused about web development scope.","web_development"
"Can you guide me through web security?","web_development"
"I need help with web development variable declarations.","web_development"
"Problem with my web server installation, can you assist?","web_development"
"Explain web cookies, I need help.","web_development"
"Stuck on a web development data structure issue.","web_development"
"Can you help me learn web development from scratch?","web_development"
"I have a question about web dev exception handling.","web_development"
"Please help me understand the web DOM.","web_development"
"I need help optimizing my web code.","web_development"
"Can you assist me in writing a web component?","web_development"
"I'm facing a problem with web development loading times.","web_development"
"Explain web promises to me, I am stuck.","web_development"
"Need a guide for web local storage.","web_development"
"Help me fix this web development syntax error.","web_development"
"I'm confused about how web browsers handle memory.","web_development"
"Can you help me with web API requests?","web_development"
"I need assistance deploying a web app.","web_development"
"Having an issue with npm install in web dev.","web_development"
"Teach me web development object oriented programming.","web_development"
"Can you guide me on web best practices?","web_development"
"I have a web development question I need help with.","web_development"
"Help me understand web strict mode.","web_development"
"I'm stuck on a web coding challenge.","web_development"
"Can you explain web modules?","web_development"
"I need help creating a web UI.","web_development"
"Problem with web recursion, please help.","web_development"
"Assist me with my web development homework.","web_development"
"I am confused by web development destructuring and need an explanation.","web_development"
"Can you help me debug a web object error?","web_development"
"I need help understanding web sets.","web_development"
"Guide me through writing a web script.","web_development"
"I have an issue with my web development environment.","web_development"
"Can you teach me web DOM manipulation?","web_development"
"Help me with this web math problem.","web_development"
"I'm stuck on web development string interpolation.","web_development"
"Explain how web imports work, I need help.","web_development"
"Can you assist me with a web array sort?","web_development"
"I have a problem understanding web lexical scoping.","web_development"
"Need help figuring out a web bug.","web_development"
"Can you guide me through web unit testing?","web_development"
"I'm confused about web development iterators.","web_development"
"Help me solve this web logic error.","web_development"
"I need assistance parsing JSON in web development.","web_development"
"Can you explain web error handling?","web_development"
"Stuck with a web package issue.","web_development"
"I have a question about web let and const.","web_development"
"Please help me with web development date and time.","web_development"
"Can you teach me web concurrency?","web_development"
"I need help writing a web while loop.","web_development"
"Guide me through web array methods.","web_development"
"I am facing an issue with web canvas plotting.","web_development"
"Help me understand web boolean logic.","web_development"
"Can you assist me with web fetch library?","web_development"
"I'm confused by web exports.","web_development"
"Problem with web indexing, need help.","web_development"
"Can you explain web slicing to me?","web_development"
"I need help building a web development project.","web_development"
"Stuck on web object attributes.","web_development"
"Help me with my web development syntax problem.","web_development"
"Can you guide me on web frameworks?","web_development"
"I have an issue running my web code.","web_development"
"Need assistance with web development input and output.","web_development"
"Can you help me understand algorithms?","programming"
"I'm stuck understanding object-oriented programming.","programming"
"Can you explain what a compiler does?","programming"
"I need help learning programming basics.","programming"
"Can you guide me through variables and functions?","programming"
"I'm confused about version control.","programming"
"Can you help me understand programming?","programming"
"I have a problem with my programming logic.","programming"
"Please assist me with this programming concept.","programming"
"I have a question regarding programming syntax.","programming"
"Could you help me fix my programming setup?","programming"
"I am stuck on a programming assignment.","programming"
"Explain how loops work in programming, please.","programming"
"I need some guidance on programming data structures.","programming"
"Can someone help me troubleshoot this programming error?","programming"
"I am confused by programming recursion.","programming"
"Having a problem getting my programming environment to run.","programming"
"Teach me how to use programming terminals.","programming"
"I need help understanding programming conditionals.","programming"
"Guide me through setting up a programming workspace.","programming"
"I'm stuck trying to understand programming paradigms.","programming"
"Can you explain why my programming logic is broken?","programming"
"I need assistance reading programming documentation.","programming"
"Help me resolve this programming type error.","programming"
"I have an issue with programming string manipulation.","programming"
"Can you help me write a programming function?","programming"
"I'm completely stuck on this programming logic.","programming"
"Need help with a programming problem right now.","programming"
"Explain programming inheritance to me, I'm confused.","programming"
"Can you teach me programming concurrency?","programming"
"I require assistance with programming arrays and lists.","programming"
"Having trouble with a programming boolean expression.","programming"
"Help me figure out this programming compile error.","programming"
"I'm confused about programming scope.","programming"
"Can you guide me through programming design patterns?","programming"
"I need help with programming variable declarations.","programming"
"Problem with my programming installation, can you assist?","programming"
"Explain programming event handling, I need help.","programming"
"Stuck on a programming data structure issue.","programming"
"Can you help me learn programming from scratch?","programming"
"I have a question about programming exception handling.","programming"
"Please help me understand the programming pointers.","programming"
"I need help optimizing my programming code.","programming"
"Can you assist me in writing a programming class?","programming"
"I'm facing a problem with programming memory management.","programming"
"Explain programming interfaces to me, I am stuck.","programming"
"Need a guide for programming local storage.","programming"
"Help me fix this programming syntax error.","programming"
"I'm confused about how programming handles data types.","programming"
"Can you help me with programming APIs?","programming"
"I need assistance deploying a programming project.","programming"
"Having an issue with package install in programming.","programming"
"Teach me programming object oriented principles.","programming"
"Can you guide me on programming best practices?","programming"
"I have a programming question I need help with.","programming"
"Help me understand programming strict mode.","programming"
"I'm stuck on a programming coding challenge.","programming"
"Can you explain programming modules?","programming"
"I need help creating a programming flowchart.","programming"
"Problem with programming recursion, please help.","programming"
"Assist me with my programming homework.","programming"
"I am confused by programming architecture and need an explanation.","programming"
"Can you help me debug a programming object error?","programming"
"I need help understanding programming sets.","programming"
"Guide me through writing a programming script.","programming"
"I have an issue with my programming environment.","programming"
"Can you teach me programming bitwise operations?","programming"
"Help me with this programming math problem.","programming"
"I'm stuck on programming string interpolation.","programming"
"Explain how programming imports work, I need help.","programming"
"Can you assist me with a programming array sort?","programming"
"I have a problem understanding programming lexical scoping.","programming"
"Need help figuring out a programming bug.","programming"
"Can you guide me through programming unit testing?","programming"
"I'm confused about programming iterators.","programming"
"Help me solve this programming logic error.","programming"
"I need assistance parsing JSON in programming.","programming"
"Can you explain programming error handling?","programming"
"Stuck with a programming package issue.","programming"
"I have a question about programming let and const.","programming"
"Please help me with programming date and time.","programming"
"Can you teach me programming threads?","programming"
"I need help writing a programming while loop.","programming"
"Guide me through programming array methods.","programming"
"I am facing an issue with programming plotting.","programming"
"Help me understand programming boolean logic.","programming"
"Can you assist me with programming libraries?","programming"
"I'm confused by programming exports.","programming"
"Problem with programming indexing, need help.","programming"
"Can you explain programming slicing to me?","programming"
"I need help building a programming project.","programming"
"Stuck on programming object attributes.","programming"
"Help me with my programming syntax problem.","programming"
"Can you guide me on programming frameworks?","programming"
"I have an issue running my programming code.","programming"
"Need assistance with programming input and output.","programming"
"Can you help me prepare for my exam?","study_help"
"I'm stuck understanding this chapter.","study_help"
"I need help making a study schedule.","study_help"
"Can you teach me active recall?","study_help"
"I'm confused about how to study for this test.","study_help"
"Can you help me study for my exam?","study_help"
"I have a problem with my study habits.","study_help"
"Please assist me with this studying technique.","study_help"
"I have a question regarding study notes.","study_help"
"Could you help me fix my study routine?","study_help"
"I am stuck on a study assignment.","study_help"
"Explain how to study better, please.","study_help"
"I need some guidance on studying for finals.","study_help"
"Can someone help me troubleshoot this study block?","study_help"
"I am confused by study methods.","study_help"
"Having a problem getting my studying done.","study_help"
"Teach me how to use study flashcards.","study_help"
"I need help understanding study techniques.","study_help"
"Guide me through setting up a study plan.","study_help"
"I'm stuck trying to study for math.","study_help"
"Can you explain why my studying isn't working?","study_help"
"I need assistance reading study materials.","study_help"
"Help me resolve this studying issue.","study_help"
"I have an issue with study memorization.","study_help"
"Can you help me write a study guide?","study_help"
"I'm completely stuck on this study topic.","study_help"
"Need help with a studying problem right now.","study_help"
"Explain study groups to me, I'm confused.","study_help"
"Can you teach me study organization?","study_help"
"I require assistance with studying for science.","study_help"
"Having trouble with a study schedule.","study_help"
"Help me figure out this study concept.","study_help"
"I'm confused about studying for history.","study_help"
"Can you guide me through study focus?","study_help"
"I need help with studying languages.","study_help"
"Problem with my study environment, can you assist?","study_help"
"Explain study breaks, I need help.","study_help"
"Stuck on a study motivation issue.","study_help"
"Can you help me learn how to study from scratch?","study_help"
"I have a question about study procrastination.","study_help"
"Please help me understand the study process.","study_help"
"I need help optimizing my study time.","study_help"
"Can you assist me in writing a study timetable?","study_help"
"I'm facing a problem with study retention.","study_help"
"Explain study recall to me, I am stuck.","study_help"
"Need a guide for study revision.","study_help"
"Help me fix this studying habit.","study_help"
"I'm confused about how studying affects grades.","study_help"
"Can you help me with study strategies?","study_help"
"I need assistance deploying a study plan.","study_help"
"Having an issue with focus in studying.","study_help"
"Teach me studying principles.","study_help"
"Can you guide me on studying best practices?","study_help"
"I have a studying question I need help with.","study_help"
"Help me understand studying requirements.","study_help"
"I'm stuck on a studying challenge.","study_help"
"Can you explain studying modules?","study_help"
"I need help creating a study flowchart.","study_help"
"Problem with studying efficiency, please help.","study_help"
"Assist me with my studying homework.","study_help"
"I am confused by studying architecture and need an explanation.","study_help"
"Can you help me debug a study error?","study_help"
"I need help understanding studying sets.","study_help"
"Guide me through writing a study script.","study_help"
"I have an issue with my studying environment.","study_help"
"Can you teach me studying operations?","study_help"
"Help me with this studying problem.","study_help"
"I'm stuck on studying interpolation.","study_help"
"Explain how studying works, I need help.","study_help"
"Can you assist me with a study sort?","study_help"
"I have a problem understanding studying scoping.","study_help"
"I need help staying motivated.","motivation"
"Can you help me stop procrastinating?","motivation"
"I'm struggling to stay focused.","motivation"
"I need assistance getting back on track.","motivation"
"Can you guide me through building discipline?","motivation"
"Can you help me stay motivated?","motivation"
"I have a problem with my motivation.","motivation"
"Please assist me with this motivation block.","motivation"
"I have a question regarding motivation techniques.","motivation"
"Could you help me fix my motivation routine?","motivation"
"I am stuck on a motivation rut.","motivation"
"Explain how to stay motivated, please.","motivation"
"I need some guidance on motivation for goals.","motivation"
"Can someone help me troubleshoot this motivation error?","motivation"
"I am confused by motivation strategies.","motivation"
"Having a problem getting my motivation up.","motivation"
"Teach me how to use motivation tools.","motivation"
"I need help understanding motivation psychology.","motivation"
"Guide me through setting up a motivation plan.","motivation"
"I'm stuck trying to find motivation.","motivation"
"Can you explain why my motivation is gone?","motivation"
"I need assistance reading motivation materials.","motivation"
"Help me resolve this motivation issue.","motivation"
"I have an issue with motivation consistency.","motivation"
"Can you help me write a motivation journal?","motivation"
"I'm completely stuck on this motivation topic.","motivation"
"Need help with a motivation problem right now.","motivation"
"Explain motivation habits to me, I'm confused.","motivation"
"Can you teach me motivation organization?","motivation"
"I require assistance with motivation for work.","motivation"
"Having trouble with a motivation schedule.","motivation"
"Help me figure out this motivation concept.","motivation"
"I'm confused about motivation for exercise.","motivation"
"Can you guide me through motivation focus?","motivation"
"I need help with motivation daily.","motivation"
"Problem with my motivation environment, can you assist?","motivation"
"Explain motivation breaks, I need help.","motivation"
"Stuck on a motivation drive issue.","motivation"
"Can you help me learn how to get motivation from scratch?","motivation"
"I have a question about motivation and procrastination.","motivation"
"Please help me understand the motivation process.","motivation"
"I need help optimizing my motivation time.","motivation"
"Can you assist me in writing a motivation timetable?","motivation"
"I'm facing a problem with motivation retention.","motivation"
"Explain motivation recall to me, I am stuck.","motivation"
"Need a guide for motivation revision.","motivation"
"Help me fix this motivation habit.","motivation"
"I'm confused about how motivation affects success.","motivation"
"Can you help me with motivation strategies?","motivation"
"I need assistance deploying a motivation plan.","motivation"
"Having an issue with focus in motivation.","motivation"
"Teach me motivation principles.","motivation"
"Can you guide me on motivation best practices?","motivation"
"I have a motivation question I need help with.","motivation"
"Help me understand motivation requirements.","motivation"
"I'm stuck on a motivation challenge.","motivation"
"Can you explain motivation modules?","motivation"
"I need help creating a motivation flowchart.","motivation"
"Problem with motivation efficiency, please help.","motivation"
"Assist me with my motivation homework.","motivation"
"I am confused by motivation architecture and need an explanation.","motivation"
"Can you help me debug a motivation error?","motivation"
"I need help understanding motivation sets.","motivation"
"Guide me through writing a motivation script.","motivation"
"I have an issue with my motivation environment.","motivation"
"Can you teach me motivation operations?","motivation"
"Help me with this motivation problem.","motivation"
"I'm stuck on motivation interpolation.","motivation"
"Explain how motivation works, I need help.","motivation"
"Can you assist me with a motivation sort?","motivation"
"I have a problem understanding motivation scoping.","motivation"
"Can you help me?","help"
"I need some assistance.","help"
"I'm stuck.","help"
"Can someone help me?","help"
"I don't know what to do.","help"
"Can you guide me?","help"
"I need help with something.","help"
"I'm confused.","help"
"I need assistance with a problem.","help"
"I have an issue.","help"
"Please assist me.","help"
"I have a question.","help"
"Could you help me fix this?","help"
"I am stuck on this.","help"
"Explain this to me, please.","help"
"I need some guidance.","help"
"Can someone help me troubleshoot this?","help"
"I am confused by this.","help"
"Having a problem getting this to run.","help"
"Teach me how to use this.","help"
"I need help understanding this.","help"
"Guide me through setting this up.","help"
"I'm stuck trying to do this.","help"
"Can you explain why this is broken?","help"
"I need assistance reading this.","help"
"Help me resolve this error.","help"
"I have an issue with this.","help"
"Can you help me write this?","help"
"I'm completely stuck on this logic.","help"
"Need help with a problem right now.","help"
"Explain this to me, I'm confused.","help"
"Can you teach me this?","help"
"I require assistance with this.","help"
"Having trouble with this.","help"
"Help me figure out this error.","help"
"I'm confused about this.","help"
"Can you guide me through this?","help"
"I need help with this.","help"
"Problem with my installation, can you assist?","help"
"Explain this, I need help.","help"
"Stuck on an issue.","help"
"Can you help me learn this from scratch?","help"
"I have a question about this.","help"
"Please help me understand this.","help"
"I need help optimizing this.","help"
"Can you assist me in writing this?","help"
"I'm facing a problem with this.","help"
"Explain this to me, I am stuck.","help"
"Need a guide for this.","help"
"Help me fix this syntax error.","help"
"I'm confused about how this handles memory.","help"
"Can you help me with this request?","help"
"I need assistance deploying this.","help"
"Having an issue with this install.","help"
"Teach me this.","help"
"Can you guide me on best practices?","help"
"I have a question I need help with.","help"
"Help me understand this mode.","help"
"I'm stuck on a challenge.","help"
"Can you explain this module?","help"
"I need help creating this UI.","help"
"Problem with this recursion, please help.","help"
"Assist me with my homework.","help"
"I am confused by this and need an explanation.","help"
"Can you help me debug this error?","help"
"I need help understanding these sets.","help"
"Guide me through writing this script.","help"
"I have an issue with my environment.","help"
"Can you teach me this manipulation?","help"
"Help me with this math problem.","help"
"I'm stuck on this interpolation.","help"
"Explain how this works, I need help.","help"
"Can you assist me with this sort?","help"
"I have a problem understanding this scoping.","help"
"Need help figuring out a bug.","help"
"Can you guide me through this unit testing?","help"
"I'm confused about these iterators.","help"
"Help me solve this logic error.","help"
"I need assistance parsing this.","help"
"Can you explain this error handling?","help"
"Stuck with a package issue.","help"
"I have a question about this.","help"
"Please help me with this date and time.","help"
"Can you teach me this concurrency?","help"
"I need help writing this loop.","help"
"Guide me through these methods.","help"
"I am facing an issue with this plotting.","help"
"Help me understand this boolean logic.","help"
"Can you assist me with this library?","help"
"I'm confused by these exports.","help"
"Problem with this indexing, need help.","help"
"Can you explain this slicing to me?","help"
"I need help building a project.","help"
"Stuck on these attributes.","help"
"Help me with my syntax problem.","help"
"Can you guide me on frameworks?","help"
"I have an issue running my code.","help"
"Need assistance with input and output.","help"
"can somebody guide me?","help"
"i need an explanation for this","help"
"having a weird issue","help"
"can u assist","help"
"im totally confused","help"
"help me solve this problem","help"
"""

new_df = pd.read_csv(io.StringIO(new_csv_content))
print(f"New examples parsed: {len(new_df)}")

for p in ["data/chatbot_training_data.csv", "ml/data/chatbot_training_data.csv"]:
    existing = pd.read_csv(p)
    combined = pd.concat([existing, new_df], ignore_index=True)
    combined.to_csv(p, index=False)
    print(f"Appended to {p} -> New total: {len(combined)} rows")
